name: JS Actions

on: [push]

jobs:
  action:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: hello-action
      uses: ./.github/actions/hello-world
 
    - name: Hello Learning Lab User
      uses: ./.github/actions/hello-world
  
    - name: Hello Mona the Octocat
      uses: ./.github/actions/hello-world
